### PR TITLE
Added 20 systems with logos

### PR DESCRIPTION
**Pull request by andresdelcampo**
Adding 20 systems with logos. Some existing with different directory name. Scraper functionality is not updated for new systems. All new pngs have a max width of 240 and max height of 100 as the rest. All work in a dark theme -added white outline.

### CODE REVIEW

**Review by NeeeeB — APPROVED** [review]
Many thanks for your contribution

**Review by NeeeeB — APPROVED** [review]

**Comment by andresdelcampo** [comment]
Thanks!! If you indicate how you figured out the scraping IDs I could add the new ones -for completion purposes. 
On another topic, I upgraded to 10.3.3 Community edition in my separate fork -not submitted yet- but I had to drop 3 themes. Let me know if interested -else I assume you prefer to keep your version and the premium themes.

**Comment by NeeeeB** [comment]
Hi Andres,
I have absolutely no problem with you modifying the source code and distributing it.
To be honest I'm even very glad you did it, because I do not have time anymore to deal with this project (life and job is too busy) and I'd like it to stay alive and if possible be updated to work on the latest recalbox version, with full options.
Regarding the scraping IDs, I don't remember how I did it, but maybe you should ask on the ScreeScraper discord, that is where I got that info (admins here are really helpful with their API)
https://discord.gg/z2E9ER4j

About the premium themes, do whatever you want, to be honest the only one I used was the Dark Slate one ^^
Now, I don't request from you to push all your modifications to this repo because I will not compile that source code anymore, so feel free to consider your fork as the "official" successor for Gamelist Editor.

;-)

**Comment by andresdelcampo** [comment]
Oh wow... I am honored!

I did not initially intend to perform very big changes to the tool, but
probably the occasional ones here and there like the deletion of videos
maybe, etc.

I find it to be the best game list editor, great looking, very practical,
and my favorite by far :). So I will be happy to put in some hours once in
a while, though not sure how often. That said, if the community's interest
sparked I guess I would respond. In the meantime I think that it will be
"back on track" with all the new systems that kept appearing over the
years.

Best regards,
Andrés

**Comment by andresdelcampo** [comment]
Hi NeeeeB,

I have sent a pull request to mention the fork in README.md, as people keep
opening issues in the original project - it is a well deserved fame, no
doubt!, though it might be good that they realize that there is another
fork currently extending it, which is not very discoverable.

Thanks!
Andrés

**Comment by andresdelcampo** [comment]
Hi  NeeeeB,

Merry Christmas!

I have made significant progress with your great tool. I thought you might
want to know...
https://github.com/andresdelcampo/GameList_Editor


   - Full Video support! with playback! -also buttons for changing and
   deleting the video. Also basic video scraping and a new Missing Videos
   filter
   - Recognize ANY system. No longer limited to a few preconfigured folder
   names.
   - Scraping is now in top shape! It now supports TLS 1.3 to be able to
   talk to the server again. The former implementation was obsolete and no
   longer working due to new security requirements from the server. It is now
   up to date.
   - Scraping is much more resilient -far less crashes when malformed XML
   or unexpected structure came from the server.
   - Languages are back better than ever! The translations were not
   included in this fork releases before (by mistake). The resources are added
   back with the latest new labels in all supported languages.
   - Adds logos and scraping info for 20 more systems: '3do', 'amiga'
   (generic), 'amigacd32', 'arcade', 'atari5200', 'atarilynx', 'cdtv',
   'coleco', 'daphne', 'gx4000', 'intellivision', 'naomi', 'neogeocd',
   'openbor', 'ports', 'saturn', 'snescd', 'x68000', 'atomiswave', 'ti99',
   'snesmsu1', 'gameandwatch', 'nds', 'odyssey2', 'tg16', 'tg16cd', 'pspminis'.
   - Active support. Feel free to open Issues or participate in Discussions
   to share feedback about the tool and make it better. Those sections are now
   available in this fork.

The only thing I am not sure it will still happen is Wine, but let's see
what people want, as so far there is mostly silence. I only realized this
week that scraping was not working -I was not using it before- and I
unintentionally had broken translations, now fixed.

Well, I hope you like what you are seeing and maybe take it for a ride at
some point. I think that today, GameList Editor is officially back to life!
:).

Best regards,
Andrés

**Comment by NeeeeB** [comment]
Hi !
Merry christmas !
Damn you did an Amazing work !!
I'm really happy to see it alive again.
Did you try and post about it in the international part of the Recalbox
forum ?
I'm pretty sure it will gain interest ;-)

Great Job by the way, it is now up to date with recent Recalbox additions.

I wish you a happy new year too !

Le dim. 26 déc. 2021 à 14:09, andresdelcampo ***@***.***> a
écrit :

> Hi NeeeeB,
>
> Merry Christmas!
>
> I have made significant progress with your great tool. I thought you might
> want to know...
> https://github.com/andresdelcampo/GameList_Editor
>
>
> - Full Video support! with playback! -also buttons for changing and
> deleting the video. Also basic video scraping and a new Missing Videos
> filter
> - Recognize ANY system. No longer limited to a few preconfigured folder
> names.
> - Scraping is now in top shape! It now supports TLS 1.3 to be able to
> talk to the server again. The former implementation was obsolete and no
> longer working due to new security requirements from the server. It is now
> up to date.
> - Scraping is much more resilient -far less crashes when malformed XML
> or unexpected structure came from the server.
> - Languages are back better than ever! The translations were not
> included in this fork releases before (by mistake). The resources are added
> back with the latest new labels in all supported languages.
> - Adds logos and scraping info for 20 more systems: '3do', 'amiga'
> (generic), 'amigacd32', 'arcade', 'atari5200', 'atarilynx', 'cdtv',
> 'coleco', 'daphne', 'gx4000', 'intellivision', 'naomi', 'neogeocd',
> 'openbor', 'ports', 'saturn', 'snescd', 'x68000', 'atomiswave', 'ti99',
> 'snesmsu1', 'gameandwatch', 'nds', 'odyssey2', 'tg16', 'tg16cd',
> 'pspminis'.
> - Active support. Feel free to open Issues or participate in Discussions
> to share feedback about the tool and make it better. Those sections are now
> available in this fork.
>
> The only thing I am not sure it will still happen is Wine, but let's see
> what people want, as so far there is mostly silence. I only realized this
> week that scraping was not working -I was not using it before- and I
> unintentionally had broken translations, now fixed.
>
> Well, I hope you like what you are seeing and maybe take it for a ride at
> some point. I think that today, GameList Editor is officially back to life!
> :).
>
> Best regards,
> Andrés
>
> On Thu, Nov 18, 2021 at 10:25 AM Andrés del Campo Novales <

**Comment by andresdelcampo** [comment]
Great idea! Done :)
https://forum.recalbox.com/topic/25736/soft-gamelist-editor-2022

Happy New Year as well!
Andrés

**Comment by andresdelcampo** [comment]
Actually, quick question... is there a reason why images have the suffix
"-image" as in *romname*-image.png instead of just *romname*.png? I was
tempted to remove it but I did not dare before looking deeper in case it
had to do with the defaulting functionality or some other reason I was not
aware of. That prefix is not something I see often...

**Comment by NeeeeB** [comment]
To be honest I do not remember why that suffix is there...maybe I copied
that behavior from UXS, the scrapper I used before...I do think you can
remove it as long as the link to the picture in the XML is modified
accordingly.

Le dim. 26 déc. 2021 à 22:40, andresdelcampo ***@***.***> a
écrit :

> Actually, quick question... is there a reason why images have the suffix
> "-image" as in *romname*-image.png instead of just *romname*.png? I was
> tempted to remove it but I did not dare before looking deeper in case it
> had to do with the defaulting functionality or some other reason I was not
> aware of. That prefix is not something I see often...
>
> On Sun, Dec 26, 2021 at 10:28 PM Andrés del Campo Novales <

**Pull request merged**
